### ISSUE TITLE
New to Open EO in R: Trouble getting job to download

### ISSUE THREAD

**Issue by zzznelsonsm** [Open-EO/openeo-community-examples#55]
Hi All,
**Thanks in advance for any help here.!!!** I am just learning openeo and am having problems despite following the examples. Here is the error message, and the code is below.

HTTP 400 Bad Request.
• SERVER-ERROR: Batch job has not finished computing the results yet. Please try again later or contact our support.list()

###Build Bounding box from Shapefile

fb <- sf::read_sf("allfb_UTM.shp")[1, ]
plot(fb)

fb_bbox = fb |>
  sf::st_bbox()

fb_bbox

# list collection and processes

list_collections()
describe_collection("SENTINEL2_L2A")

list_processes()

p <- processes()
datacube <- p$load_collection(
  id = "SENTINEL2_L2A",
  spatial_extent= fb_bbox,
  temporal_extent=list("2024-07-01", "2024-07-16"),
  bands=list('B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B09', 'B11', 'B12')
)

evi_cube <- p$reduce_dimension(data = datacube, dimension = "bands",reducer = function(data,context) {
  B08 = data[1]
  B04 = data[2]
  B02 = data[3]
  (2.5 * (B08 - B04)) / sum(B08, 6.0 * B04, -7.5 * B02, 1.0)
})

temporal_reduce_evi <- p$reduce_dimension(data=evi_cube,dimension = "t", reducer = function(x,y){
  max(x)
})

job <- create_job(graph=temporal_reduce_evi,title = "EVI using R client")

start_job(job = job)

download_results(job = job, folder = "C:/Users/scott/OneDrive/Desktop/Consulting/Becks/Seed Fields/CI")

**Comment by jdries** [comment]
Hi,
this simply looks as if your job started successfully, and you need to wait a bit longer for it to finish before you can actually download results.
For a user interface that shows the job status, and also for easy download, you can open 'https://openeo.dataspace.copernicus.eu" in your web browser and log in.
